#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable
CC        = nvcc
OPTIMIZE  = yes
DEBUG     = no
ARCH      = sm_70
#MPI_ROOT  = usrlibx86_64-linux-gnuopenmpi
#LAUNCHER  = usrbinmpirun -n 1
MPI_ROOT  = optnvidiahpc_sdkLinux_x86_6424.5comm_libs12.4openmpi4openmpi-4.1.5
LAUNCHER  = optnvidiahpc_sdkLinux_x86_6424.5comm_libsmpibinmpirun -n 2

#===============================================================================
# Program name & source code list
#===============================================================================

program = main

source = main.cu collectives.cu timer.cu

obj = $(source.cu=.o)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS = $(EXTRA_CFLAGS) -std=c++17 -I$(MPI_ROOT)include -DOMPI_SKIP_MPICXX= 
          -Xcompiler -Wall -arch=$(ARCH)

# Linker Flags
LDFLAGS = -L$(MPI_ROOT)lib -lmpi -DOMPI_SKIP_MPICXX=

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -DDEBUG
  LDFLAGS  += -g
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif
#===============================================================================
# Targets to Build
#===============================================================================

$(program) $(obj) Makefile
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o %.cu .h Makefile
	$(CC) $(CFLAGS) -c $ -o $@

clean
	rm -rf $(program) $(obj)

run $(program)
	$(LAUNCHER) .$(program)
